/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor5 from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import cmsAnalyzer from "@exfabrica/strapi-plugin-awesome-seo/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiCodeEditorCustomField from "strapi-code-editor-custom-field/strapi-admin";
import strapiGoogleAuth from "strapi-google-auth/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor5: ckeditor5,
    "cms-analyzer": cmsAnalyzer,
    "strapi-cloud": strapiCloud,
    graphql: graphql,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "strapi-code-editor-custom-field": strapiCodeEditorCustomField,
    "strapi-google-auth": strapiGoogleAuth,
    "rest-cache": restCache,
  },
});
